version: '3.8'

services:
  botpress:
    build:
      context: .
    container_name: botpress
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      DATABASE_URL: postgres://user:password@db:5432/botpress
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: botpress-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: botpress
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
